<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PiezasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $piezas = [
            [
                'nombre' => 'Bujía NGK Iridium',
                'numero_parte' => 'BKR6EIX-11',
                'descripcion' => 'Bujía de alto rendimiento para motores a gasolina',
                'marca' => 'NGK',
                'precio' => 180.00,
                'stock' => 40,
                'categoria' => 'Encendido',
                'vehiculo_compatible' => 'Nissan, Toyota, Honda',
                'proveedor' => 'Refaccionaria México',
                'imagen_url' => null,
                'activo' => true,
                'disponibilidad' => 'En stock',
                'especificaciones' => json_encode(['tipo'=>'Iridium','rosca'=>'14mm']),
            ],
            [
                'nombre' => 'Filtro de Aceite Fram PH6607',
                'numero_parte' => 'PH6607',
                'descripcion' => 'Filtro de aceite para motor',
                'marca' => 'Fram',
                'precio' => 95.00,
                'stock' => 30,
                'categoria' => 'Filtros',
                'vehiculo_compatible' => 'Nissan Versa, March',
                'proveedor' => 'AutoZone',
                'imagen_url' => null,
                'activo' => true,
                'disponibilidad' => 'En stock',
                'especificaciones' => json_encode(['altura'=>'85mm','diámetro'=>'65mm']),
            ],
            [
                'nombre' => 'Pastillas de Freno Bosch QuietCast',
                'numero_parte' => 'BC905',
                'descripcion' => 'Juego de pastillas de freno delanteras',
                'marca' => 'Bosch',
                'precio' => 780.00,
                'stock' => 15,
                'categoria' => 'Frenos',
                'vehiculo_compatible' => 'Chevrolet Aveo, Sonic',
                'proveedor' => 'Refaccionaria Express',
                'imagen_url' => null,
                'activo' => true,
                'disponibilidad' => 'En stock',
                'especificaciones' => json_encode(['material'=>'Cerámica']),
            ],
            [
                'nombre' => 'Amortiguador Monroe Original',
                'numero_parte' => 'MON-37221',
                'descripcion' => 'Amortiguador delantero para suspensión',
                'marca' => 'Monroe',
                'precio' => 1250.00,
                'stock' => 10,
                'categoria' => 'Suspensión',
                'vehiculo_compatible' => 'Volkswagen Jetta',
                'proveedor' => 'Suspensiones México',
                'imagen_url' => null,
                'activo' => true,
                'disponibilidad' => 'En stock',
                'especificaciones' => json_encode(['tipo'=>'Hidráulico']),
            ],
            [
                'nombre' => 'Batería LTH 48-600',
                'numero_parte' => 'LTH-48-600',
                'descripcion' => 'Batería automotriz 48 meses de garantía',
                'marca' => 'LTH',
                'precio' => 2450.00,
                'stock' => 8,
                'categoria' => 'Eléctrico',
                'vehiculo_compatible' => 'General',
                'proveedor' => 'LTH México',
                'imagen_url' => null,
                'activo' => true,
                'disponibilidad' => 'En stock',
                'especificaciones' => json_encode(['CCA'=>'600','voltaje'=>'12V']),
            ],
            [
                'nombre' => 'Llanta Michelin Primacy 4',
                'numero_parte' => 'MICH-195/65R15',
                'descripcion' => 'Llanta para auto compacto, excelente agarre',
                'marca' => 'Michelin',
                'precio' => 2850.00,
                'stock' => 20,
                'categoria' => 'Llantas',
                'vehiculo_compatible' => 'Nissan Sentra, Toyota Corolla',
                'proveedor' => 'Michelin México',
                'imagen_url' => null,
                'activo' => true,
                'disponibilidad' => 'En stock',
                'especificaciones' => json_encode(['tamaño'=>'195/65R15','índice_carga'=>'91H']),
            ],
            [
                'nombre' => 'Disco de Freno Bendix',
                'numero_parte' => 'BDX-PRT5394',
                'descripcion' => 'Disco de freno delantero ventilado',
                'marca' => 'Bendix',
                'precio' => 650.00,
                'stock' => 12,
                'categoria' => 'Frenos',
                'vehiculo_compatible' => 'Ford Focus, Fiesta',
                'proveedor' => 'Frenos México',
                'imagen_url' => null,
                'activo' => true,
                'disponibilidad' => 'En stock',
                'especificaciones' => json_encode(['diámetro'=>'280mm','grosor'=>'25mm']),
            ],
            [
                'nombre' => 'Bomba de Agua Gates',
                'numero_parte' => 'GAT-41022',
                'descripcion' => 'Bomba de agua para sistema de enfriamiento',
                'marca' => 'Gates',
                'precio' => 1150.00,
                'stock' => 8,
                'categoria' => 'Motor',
                'vehiculo_compatible' => 'Volkswagen Beetle, Jetta',
                'proveedor' => 'Gates México',
                'imagen_url' => null,
                'activo' => true,
                'disponibilidad' => 'En stock',
                'especificaciones' => json_encode(['material'=>'Aluminio','presión_máx'=>'15 PSI']),
            ],
            [
                'nombre' => 'Alternador Bosch Reman',
                'numero_parte' => 'AL9960X',
                'descripcion' => 'Alternador remanufacturado 90 amperes',
                'marca' => 'Bosch',
                'precio' => 1950.00,
                'stock' => 6,
                'categoria' => 'Eléctrico',
                'vehiculo_compatible' => 'Chevy, Aveo',
                'proveedor' => 'Bosch México',
                'imagen_url' => null,
                'activo' => true,
                'disponibilidad' => 'En stock',
                'especificaciones' => json_encode(['amperaje'=>'90A','voltaje'=>'12V']),
            ],
            [
                'nombre' => 'Kit de Clutch LUK',
                'numero_parte' => 'LUK-624317600',
                'descripcion' => 'Kit de embrague completo con disco, prensa y balero',
                'marca' => 'LUK',
                'precio' => 3200.00,
                'stock' => 5,
                'categoria' => 'Transmisión',
                'vehiculo_compatible' => 'Volkswagen Jetta, Golf',
                'proveedor' => 'LUK México',
                'imagen_url' => null,
                'activo' => true,
                'disponibilidad' => 'En stock',
                'especificaciones' => json_encode(['diámetro_disco'=>'228mm','tipo'=>'Orgánico']),
            ]
        ];

        foreach ($piezas as $pieza) {
            \App\Models\Pieza::create($pieza);
        }
    }
}
